// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFilePaths():Promise<Array<string>>;

export function ReadImageToBase64(arg1:string):Promise<string>;

export function ReadImages():Promise<Array<string>>;
